### PR TITLE
[wip] Add python linting.

### PR DESCRIPTION
**Pull request by jmcarp**
Work in progress. Begins support for python linting with flake8.

[addresses #463]

### CODE REVIEW

**Comment by jmcarp** [comment]
Tests are passing locally--not sure why this didn't trigger a build on Travis. If the patch is of interest, I'm happy to expand tests and documentation.
@salbertson @gylaz

**Comment by teoljungberg** [comment]
Thanks for working on this @jmcarp, we're currently going through architechtual changes in Hound and we're holding off adding new languages until that has landed.

References #727

**Comment by jmcarp** [comment]
Cool, happy to update the PR once the new architecture is settled.

**Comment by salbertson** [comment]
@jmcarp, thank you for being patient! We definitely see Python support being a huge addition to Hound.

**Comment by salbertson** [comment]
@jmcarp we finally settled on the architecture and have moved SCSS review to a service. Check out https://github.com/thoughtbot/hound-scss for reference.

I think Python support would be great.

**Comment by jmcarp** [comment]
@salbertson the new architecture looks great! I submitted an updated patch in #853.

**Pull request closed without merging**
