### PR TITLE
Lint `coffee.erb` files

### PR DESCRIPTION
**Pull request by teoljungberg**
https://trello.com/c/3zlQD21q

### CODE REVIEW

**Comment by gylaz** [comment]
Seems good to me. :+1:

**Comment by salbertson** [comment]
Woohoo. :+1:

**Comment by salbertson** [comment]
We should let users know about this.

**Comment by teoljungberg** [comment]
> We should let users know about this.

Absolutely, how do we handle communications like that? Tweet it out?
/cc @croaky

**Comment by gylaz** [comment]
We typically tweet about minor things, and write up a blog post about more major features. We can also ping directly the people that have asked about this feature.

**Comment by salbertson** [comment]
@teoljungberg, looks good, merge when you're ready.

**Comment by teoljungberg** [comment]
I'll merge it and queue a tweet into buffer

**Pull request merged**
