### PR TITLE
Fix rules for indenting multiline assignments

### PR DESCRIPTION
**Pull request by graysonwright**
https://trello.com/c/8plKSKKM

See https://github.com/bbatsov/rubocop/issues/1633

### CODE REVIEW

**Comment by jakecraige** [comment]
:+1:

**Comment by gylaz** [comment]
Do you mind also adding in to thoughtbot's config?

**Comment by gylaz** [comment]
@salbertson What are your thoughts on also making this change in default? It would mean drifting away from RuboCop's default, but this is really an ugly setting. I fear I might be getting too personally attached to the defaults.

**Comment by salbertson** [comment]
@gylaz, I don't think we should be affecting existing users by updating defaults, unless we think it's important enough and we communicate the change to everyone.

**Comment by salbertson** [comment]
@graysonwright, should this be added to the thoughtbot config too? Maybe in a different PR?

This looks good to me. :+1:

**Comment by teoljungberg** [comment]
Our styleguide is not updated for this https://github.com/thoughtbot/guides/blob/master/style/README.md#formatting
We should open a PR to thoughtbot/guides before changing it in Hound, everyone at thoughtbot doens't follow the developments made in Hound but they watch Guides.
I personally don't agree with this styleguide and would like it to be discussed, if the majority is in favor of this - we keep it. If not, let's chage it back to the defaults

ping @thoughtbot/hound @jferris @graysonwright

**Comment by gylaz** [comment]
@teoljungberg Just to clarify you prefer:
```rb
users = User.where(email: 'user@example.com').
             update(user_parameters)
```
This PR changes this to favor:
```rb
users = User.where(email: 'user@example.com').
  update(user_parameters)
```
And while it might not be explicitly in our guides, 99% of thoughtbot code follows the latter.

**Comment by gylaz** [comment]
Actually, we do have a guideline for it:

> Indent continued lines two spaces.

**Comment by teoljungberg** [comment]
Actually no, this rule enforces this style (sorry for a shitty example, typing from my phone)


users = Users.
               active.
               awesome.
               tall

---
Teo Ljungberg

**Comment by gylaz** [comment]
@teoljungberg Can you clarify where you're getting your information from? This comment https://github.com/bbatsov/rubocop/issues/1633#issuecomment-73067109 seems to be inline with what I've said, and the general spirit of this PR.

**Comment by teoljungberg** [comment]
@gylaz I pinged you in the repo where we have the problem

**Comment by gylaz** [comment]
I don't know what's going on on that related PR. I've added unit tests for this setting in #772.

**Pull request merged**
