### PR TITLE
Upgrade Rubocop to `v0.35.1`

### PR DESCRIPTION
**Pull request by teoljungberg**
https://trello.com/c/C9w8zdW7

### CODE REVIEW

**Comment by thorncp** [comment]
LGTM :watermelon:

**Comment by gylaz** [comment]
:ship:

**Comment by gylaz** [comment]
Should we close this now that https://github.com/thoughtbot/hound/pull/1034 is up?

**Comment by teoljungberg** [comment]
Closing this in favor of #1034

**Pull request closed without merging**
