### PR TITLE
Upgrade ruby to 2.3.0

### PR DESCRIPTION
**Pull request by gylaz**

### CODE REVIEW

**Comment by gylaz** [comment]
Sanity tested on staging.

**Comment by teoljungberg** [comment]
According to the output from CircleCI, there are some new warnings.

```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.x-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

Could these be addressed before merging this PR?

**Comment by gylaz** [comment]
Done, by upgrading `parser`.

**Comment by croaky** [comment]
Looks good

**Pull request merged**
