### PR TITLE
Add Python documentation

### PR DESCRIPTION
**Pull request by thorncp**
Since we announced the beta, we should have some information about it.

### CODE REVIEW

**Comment by teoljungberg** [comment]
Could you provide screenshots?

**Comment by thorncp** [comment]
Sure!

configuration___hound

**Comment by teoljungberg** [comment]
LGTM

**Comment by pmart123** [comment]
Could you perhaps put an example implementation of a flake8.ini?  Admittedly, I haven't put too much thought into it, but my implementation seemed to hang hound on a pull request just by specifying max_line_length in the ini file.

**Pull request merged**
