### PR TITLE
Remove Stripe event listener

### PR DESCRIPTION
**Pull request by salbertson**
The webhook was never set up in Stripe. I think we can handle failed charges by hand until it becomes an issue.

### CODE REVIEW

**Comment by croaky** [comment]
Red everywhere. As far as the eye can see.

**Comment by croaky** [comment]
Looks good to me.

**Comment by cpytel** [comment]
I recommend using churnbuster to help with this. We use it on Upcase and FormKeep.

**Comment by gylaz** [comment]
What is the process of handling this by hand? Would be helpful to document this somewhere.

**Pull request merged**
