### PR TITLE
Remove disabling of cops for thoughtbot Ruby config

### PR DESCRIPTION
**Pull request by gylaz**
IIRC, the original decision to disable these was because they were not explicitly
specified in our style guide. The default RuboCop configuration is pretty good.
We should only override the things we don't agree with, rather than disabling
the cops that are not in our style guide.

### CODE REVIEW

**Comment by gylaz** [comment]
@jferris your thoughts on this?

**Comment by salbertson** [comment]
I like it. :+1:

**Comment by salbertson** [comment]
@gylaz, what's the latest with this?

**Comment by gylaz** [comment]
Wanted to see if @jferris had anything to say about this.

**Comment by salbertson** [comment]
@croaky is there anything that would be enabled by this change that you think is a deal breaker? I want to make sure we aren't enabling something that would surprise most users, in a bad way.

**Comment by tute** [comment]
I was just working with some rubocop output and thought "why did hound never tell me this?". I like this change.

**Comment by jferris** [comment]
I don't think we should do this. I would actually prefer that cops were not added until we enable them proactively.

Every time Hound makes a comment which isn't in line with our guides, it decreases our success with Hound. A pull request submitter will likely choose to ignore the comment (since our guides don't support what Hound is saying), which makes people get more used to ignoring Hound. In turn, this worsens the signal-to-noise ratio for Hound comments.

The extra noise gives ammunition to nay-sayers. Every comment by Hound which doesn't produce value for us creates a situation in which some of us will question whether or not to use Hound in the future.

It's been enough of a battle to get people to agree to almost anything in the style guide. It's been an additional fight to get people to accept Hound enforcing that guide. Having Hound automatically start commenting with new requirements we never agreed to starts yet another fight.

I short, I would prefer to be conservative, because I think these comments will start arguments instead of discussions.

**Comment by mcmire** [comment]
I agree with @jferris on this, good reasoning.

**Comment by salbertson** [comment]
@jferris, sounds good.

Here's the entire [default Hound config](https://github.com/thoughtbot/guides), maybe the thoughtbot version should be part of https://github.com/thoughtbot/guides? That way it's very clear what is enabled and thoughtbot repos won't be affected by changes to RuboCop or Hound defaults.

Let me know if that sounds like a good idea and I'll open a PR.

**Comment by jferris** [comment]
> maybe the thoughtbot version should be part of https://github.com/thoughtbot/guides?

Yes, [I'd love that](https://github.com/thoughtbot/hound/issues/293)!

**Pull request closed without merging**
