### PR TITLE
Update development setup and docs

### PR DESCRIPTION
**Pull request by thorncp**
* Update setup docs for local development
* Setup .env file before the database

https://trello.com/c/k4YvjQxP

### CODE REVIEW

**Comment by thorncp** [comment]
Ugh, didn't realize the https change would break so many specs. I'll look into them.

**Comment by srt32** [comment]
Looks like travis is not happy. Did tests work locally?

**Comment by gylaz** [comment]
Looks sane to me.

**Comment by srt32** [comment]
LGTM

**Pull request merged**
