### PR TITLE
Offer bulk pricing

### PR DESCRIPTION
**Pull request by croaky**
* Provide details about bulk pricing in FAQ.
* Group subscription-related questions together.

### CODE REVIEW

**Comment by croaky** [comment]
Added bulk pricing info to homepage:

screen shot 2015-02-27 at 10 31 59 am

**Comment by thorncp** [comment]
LGTM :tophat:

**Comment by salbertson** [comment]
@croaky were the SCSS comments useful? @frechg do these comments follow our style guide?

**Comment by frechg** [comment]
@salbertson @croaky most of the scss comments I've gotten are useful. Some could be explained more clearly. The "Selector should have depth of applicability no greater than..." comments are not that great. Not because they don't help to keep things clean but because they aren't very clear and solutions to them are more involved than most style comments. A lot of the time if I am nesting something too deep, which I assume is what "Selector depth of applicability" refers to, it's going to take some rethinking of larger styles architecture to improve/fix.

**Pull request merged**
