### PR TITLE
Don't have Foreman start Redis

### PR DESCRIPTION
**Pull request by salbertson**

### CODE REVIEW

**Comment by croaky** [comment]
Looks good.

**Comment by salbertson** [comment]
@croaky, updated readme too.

**Comment by gylaz** [comment]
It would be great to include an explanation in the commit message of what the issue with starting Redis via foreman was.

**Comment by salbertson** [comment]
@frechg ran into an issue over the weekend, which I've also run into before, where starting Hound with Foreman fails because Redis server is already running.

**Pull request merged**
