### PR TITLE
Use ngrok url in .env.sample

### PR DESCRIPTION
**Pull request by dbackeus**
Make it conform with the README and avoid having a host which github webhooks can't reach.

### CODE REVIEW

**Comment by teoljungberg** [comment]
Could you add in an update to the README asking the user to fill in the .env file aswell?

**Comment by teoljungberg** [comment]
Looks great! I'll merge when you either rebase against master or squash the commits into 1

**Comment by dbackeus** [comment]
@teoljungberg done

**Comment by teoljungberg** [comment]
Thank you!

**Pull request merged**
