### PR TITLE
Remove `StyleConfig`

### PR DESCRIPTION
**Pull request by teoljungberg**
We decided not to save the configuration in the database.

https://trello.com/c/pDvJ8BbS

### CODE REVIEW

**Comment by arunagw** [comment]
If this table is empty on production and not used anywhere else.. this looks fine to me.

**Comment by teoljungberg** [comment]
The table is empty in production:

```
hound-production::SILVER=> select * from style_configs;
(No rows)
```

**Comment by arunagw** [comment]
Also is `Owner` table used anywhere? I can see it gets filled but is it used anywhere?

**Comment by arunagw** [comment]
But we can do `Owner` table in another PR or issue

**Comment by teoljungberg** [comment]
@arunagw Since the `Owner` is pretty coupled with the `StyleConfig` - I opted to delete the owner here aswell.

**Comment by arunagw** [comment]
Sounds good. Let's wait for more review here before merging this in master.

**Comment by thorncp** [comment]
Yep, `Owner` was introduced as a precursor to organization level config. See #586. I don't think it was ever used for anything else, but perhaps someone is using it for statistics? @gylaz or @salbertson ? If not, is there meaningful data we can get from it that we aren't?

**Comment by salbertson** [comment]
`Owner` is not being used for stats. Why are we removing the owner code? Is it causing issues?

**Comment by teoljungberg** [comment]
I opted to delete it since it's dormant code, we're not using it for anything.

Will we? Or does it only make sense to delete the style-config?

---
Teo Ljungberg

**Comment by gylaz** [comment]
`Owner` was added to back fill information about GitHub users/orgs. We will be adding org-level configuration soon-ish, so this is probably good to keep. As for `StyleConfig`, I believe it can be removed.

**Comment by teoljungberg** [comment]
@gylaz Changed in 1f79b79

**Comment by gylaz** [comment]
:+1:

**Pull request merged**
