### PR TITLE
Disable quote checking by default

### PR DESCRIPTION
**Pull request by salbertson**
Commenting on double or single quotes has surprised some users. I think it's best to disable the check by default and let each team choose which type of quotes they would like Hound to enforce.

### CODE REVIEW

**Comment by salbertson** [comment]
@gylaz, thoughts?

**Comment by salbertson** [comment]
I was thinking we should get this in before https://github.com/thoughtbot/hound/pull/617.

**Comment by srt32** [comment]
Is is right that this change will disable quote checking for all active repos
without a custom config overriding the default?

**Comment by salbertson** [comment]
Yes, I don't think it's worth it.

**Comment by croaky** [comment]
I think we want to do this, but not for existing repos, and only after we've moved the server-side config into the db.

**Comment by srt32** [comment]
Agreed!

**Pull request closed without merging**
