### PR TITLE
Use rails 4.2.5

### PR DESCRIPTION
**Pull request by arunagw**

### CODE REVIEW

**Comment by thorncp** [comment]
LGTM but will need some smoke testing on staging. I'll get around to that soon.

**Comment by arunagw** [comment]
Great! thanks

**Comment by gylaz** [comment]
I'm getting a:
```
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'momentjs-rails'
```
when running `bundle install` locally.

**Comment by gylaz** [comment]
Closing this in favor of https://github.com/thoughtbot/hound/pull/1022, where I've made further progress.

**Comment by arunagw** [comment]
:+1:

**Pull request closed without merging**
