### PR TITLE
Add collaborators directly to private repos

### PR DESCRIPTION
**Pull request by salbertson**
This change takes advantage of the new GitHub permissions and adds `houndci` as a collaborator instead of trying to create a Services team and adding `houndci`.

https://github.com/blog/2064-new-organization-permissions-now-available

### CODE REVIEW

**Comment by thorncp** [comment]
This is awesome!

**Comment by teoljungberg** [comment]
Should we have a migration plan for removing the previous `Service` team?

**Comment by salbertson** [comment]
@teoljungberg we decided not to try and remove the Services team.

**Comment by salbertson** [comment]
@thorncp this is working on staging. Want to give it another review?

**Comment by thorncp** [comment]
Still LGTM :+1:

**Pull request merged**
