### PR TITLE
Fix bundler caching on Travis to speed up builds

### PR DESCRIPTION
**Pull request by croaky**
Trying technique noted on:

https://github.com/thoughtbot/suspenders/pull/567#issuecomment-109330176

### CODE REVIEW

**Comment by croaky** [comment]
Not entirely sure if this works on an open source repo. Will see what the results are.

**Comment by croaky** [comment]
Looks like we're switching to Circle instead.

**Comment by iwz** [comment]
Did you switch to circle because of this issue?

**Comment by croaky** [comment]
@iwz No, more because Hound is open source, it's on the free OSS tier for Travis, which gets backed up. Circle has been faster to start builds.

**Pull request closed without merging**
