### PR TITLE
Go linter

### PR DESCRIPTION
**Pull request by kirs**
As we discussed in #435
Requires `go` and `golint` installed on server.

### CODE REVIEW

**Comment by gylaz** [comment]
@croaky @srt32 @bernerdschaefer Do you think that it would be useful in having Hound support Go?

**Comment by srt32** [comment]
@gylaz I think now is not a great time for us to begin Go support. Given our focus on stability and languages for which we know we have user demand perhaps we should revisit this idea in a few months. Regardless, @kirs thanks for putting together this PR!

**Comment by croaky** [comment]
> Given our focus on stability and languages for which we know we have user demand perhaps we should revisit this idea in a few months. 

I think we've addressed most stability issues at this point? This thread is also showing the user demand for this language?

**Comment by gylaz** [comment]
> This thread is also showing the user demand for this language?

Can you expand on this more, @croaky? The only person outside of our team to comment on this thread is the original PR creator.

**Comment by salbertson** [comment]
@kirs, I opened a new PR with a couple updates. https://github.com/thoughtbot/hound/pull/678

**Pull request closed without merging**
