### PR TITLE
Update SCSSLint

### PR DESCRIPTION
**Pull request by teoljungberg**
- Update SCSS config
- Due to a change in `0.35.0`, we have to support create an actual file
  for each file we want to lint. This is being handled by creating a
  tempfile and then unlinking it after each run

### CODE REVIEW

**Comment by teoljungberg** [comment]
We're currently discussing in brigade/scss-lint#435 if we can
re-implement support for giving `SCSSLint::Runner#run` file contents
aswell as proper files

**Comment by gylaz** [comment]
Looks good.

**Comment by teoljungberg** [comment]
I'm going to let this sit until we see what happeneds with
https://github.com/brigade/scss-lint/issues/435

**Comment by thorncp** [comment]
Closing this since SCSS is now a worker. Created https://github.com/thoughtbot/hound-scss/issues/10 in its stead.

**Pull request closed without merging**
