### PR TITLE
Update rails gem for security

### PR DESCRIPTION
**Pull request by camelmasa**
See.
http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/

### CODE REVIEW

**Comment by arunagw** [comment]
Looks good to me

**Comment by thorncp** [comment]
@camelmasa Do you mind bumping this to 4.2.3?

**Comment by camelmasa** [comment]
@thorncp Yeah we should update that :octocat: I'll update this PR. Thank you :+1:

**Comment by camelmasa** [comment]
This PR is passed tests on my PC. But, The tests aren't passed on Circle CI.
I asked about issue to Circle CI. I'm waiting for that.

Please merge it if don't need to wait a response from Circle CI.

**Comment by thorncp** [comment]
I poked around in it a little. It seems like Circle's `pre` [hook](https://github.com/camelmasa/hound/blob/0b17ad5fa058eaad186e5df0082842cf026012f3/circle.yml#L3) isn't firing

**Comment by camelmasa** [comment]
@thorncp Yes, I think so too. I shared the issue to Circle CI.

**Comment by thorncp** [comment]
I submitted a potential fix in #850

**Comment by thorncp** [comment]
@camelmasa #850 just merged, which I believe will solve the CI problem here. Do you mind rebasing on top of master once again?

**Comment by thorncp** [comment]
I wanted to get this merged and deployed before I left for the day. Merged as ef65d0cbe0a81a676590824ee3151041b90629ec

**Comment by camelmasa** [comment]
Sorry for late. Thank you for merging :+1:

**Pull request closed without merging**
