### PR TITLE
Update dotenv-rails

### PR DESCRIPTION
**Pull request by teoljungberg**
To quell warning:
```
Auto-loading of `.env.test` will be removed in 1.0. See
"https://github.com/bkeepers/dotenv-deployment" if you would like to
continue using this feature.
```

`dotenv-deployment` is deprecated, so updating `dotenv-rails` quells the warning

### CODE REVIEW

**Comment by gylaz** [comment]
`dotenv-deployment` is deprecated. I don't think it's worth adding another, deprecated gem in this case. Does updating `dotenv-rails` get rid of the warning? (You'll also have to upgrade `foreman` first).

**Comment by teoljungberg** [comment]
That worked perfectly @gylaz fixed in a69c53a

**Comment by gylaz** [comment]
Great! Mind updating the commit (and the PR) message/description? Then ready to merge.

**Comment by thorncp** [comment]
LGTM!

**Pull request merged**
