### PR TITLE
Use separate resque processes for high and medium/low queues

### PR DESCRIPTION
**Pull request by salbertson**
This should prevent a busy queue from blocking medium and low queue items.

### CODE REVIEW

**Comment by gylaz** [comment]
I would rather just use one queue name than add more worker types. I don't think we have a good reason to use differently named queues, and it's just one more thing to manage in Heroku.

**Comment by salbertson** [comment]
We introduced priority to prevent large build jobs from blocking other jobs like repo refreshes, org invites and small builds. Are you suggesting we lump all jobs together?

**Comment by thorncp** [comment]
When we introduced the SOA, we put the `CompletedFileReview` as high priority. Since we only have one procfile entry for all the queues, the works will focus on finalizing reviews, and will not spend time reviewing files. This is effectively turning our asynchronous architecture into a synchronous one, because the workers review a chunk of builds, then finalize a chunk of builds. If we split out workers for each queue, we can always be working instead of getting clogged up:

resque_

**Comment by thorncp** [comment]
What do you think about a config like this?

```
resque_high: ... QUEUE=high,medium ...
resque_medium: ... QUEUE=medium ...
resque_low: ... QUEUE=low,medium ...
```

This would allow us to always be working off jobs on each queue and the `high` and `low` workers can handle `medium` jobs if there's no pending `high` or `low` jobs.

**Pull request merged**
