### PR TITLE
Pass the parameters in the same order as the api client

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by arunagw** [comment]
We were sending wrong parameters from here https://github.com/thoughtbot/hound/blob/master/app/models/github_team.rb#L18

But now they are flipped should be good

**Comment by gylaz** [comment]
:+1:

**Comment by salbertson** [comment]
:+1:

**Comment by salbertson** [comment]
Restarted build.

**Comment by teoljungberg** [comment]
Closing in favor of #659

**Pull request closed without merging**
