### PR TITLE
Disable SCSS property count linter

### PR DESCRIPTION
**Pull request by tysongach**
https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertycount

### CODE REVIEW

**Comment by gylaz** [comment]
LGTM, but I'm curious what's the story/rational behind this?

**Comment by tysongach** [comment]
I don’t think property count is a big enough issue/code smell to warrant a comment from Hound.

**Comment by joshuaogle** [comment]
:+1: I agree. It could theoretically be a smell, but the vast majority of the time it would be flagging on legitimate uses.

**Comment by tysongach** [comment]
@gylaz Do we know why builds are failing here and on `master`?

**Comment by teoljungberg** [comment]
@tysongach it's a random build-failure we're having. We're working on getting it fixed

**Comment by tysongach** [comment]
@teoljungberg Cool. Good to go ahead an merge this? I was failing at one point…

**Pull request merged**
