### PR TITLE
Disable Raven in test environment

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by gylaz** [comment]
Is the benefit that the exceptions now get displayed in the console?

**Comment by teoljungberg** [comment]
The main reason for me was to remove the logging to STDOUT, which made running tests with`vim-dispatch` not as easy

**Comment by croaky** [comment]
How about moving Raven to only staging and production environments? e80491e

**Comment by thorncp** [comment]
LGTM

**Pull request merged**
