### PR TITLE
Bumps Rubocop to 0.36

### PR DESCRIPTION
**Pull request by BenMorganIO**
This adds support for ruby 2.3.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Looks like the tests are failing from the HAML linter.

**Comment by gylaz** [comment]
We are in the process of upgrading RuboCop, it's not as striaigh forward as just upgrading the gem since there were rules renamed and removed. We'll likely have this done sometime next week.

**Comment by BenMorganIO** [comment]
@gylaz yep, saw those changes on a personal project. Was also going to target those after seeing CircleCI's output :p

The ruby parser seems to be the initial problem for CircleCI right now. Trying to solve that atm.

**Comment by gylaz** [comment]
Closing this in favor of https://github.com/thoughtbot/hound/pull/1034.

**Pull request closed without merging**
