### PR TITLE
WIP: Comment on commit messages

### PR DESCRIPTION
**Pull request by Koronen**
This code implements (parts of) the functionality discussed in #394. The discussion ended rather quickly, but I decided to go ahead and implement it.

I've been sitting on this code for a couple of months now, and I though I might as well share it. While the pre-squash-and-rebase version of it has been running smoothly on a separate instance, there are some things I'd like to fix with the current implementation. One such thing is to make this functionality opt-in (as mentioned in #394).

I'd love some more feedback on this. Mainly, is there sufficient interest in seeing this feature completed?

### CODE REVIEW

**Comment by salbertson** [comment]
@Koronen, a few users have mentioned they don't use Pull Requests and they would like Hound to review commits that aren't part of a Pull Request.

Is that what this change does?

According to existing users it's a good idea. @gylaz, thoughts?

**Comment by Koronen** [comment]
@salbertson no, I believe that would be #468. This PR adds support for linting commit messages, like checking to see if the subject line exceeds the [recommended maximum of 50 characters](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).

**Comment by salbertson** [comment]
@Koronen, ah, ok. Thanks for clarifying.

I wouldn't want Hound to comment on poorly formatted commit messages. For one, the commit message doesn't live on in the source code and wouldn't decrease readability like inconsistent code style can.

Second, I'm not sure there is enough consensus around what makes a "good" commit message. That means we would have to disable it by default, which I would rather not do.

@Koronen, thanks for the PR but I don't think we will be merging this.

@gylaz, thoughts?

**Comment by gylaz** [comment]
@Koronen Thanks for the PR. Lets revisit this later when we support more languages. I'm going to close it for now.

**Pull request closed without merging**
