### PR TITLE
Upgrade scss-lint gem

### PR DESCRIPTION
**Pull request by salbertson**
Trying to get rid of `undefined method bubbles?` exception.

https://github.com/causes/scss-lint/issues/278

This worked locally so we'll see if it runs successfully on TravisCI.

screenshot 2015-01-26 08 51 48

### CODE REVIEW

**Comment by gylaz** [comment]
Have we tried upgrading the gem to see if the errors would go away? @thorncp Had a reproducible seed on a branch we can test against.

**Comment by salbertson** [comment]
@gylaz, that's a good idea, ha. I haven't tried.

What branch? I'll try out both potential fixes.

**Comment by salbertson** [comment]
That didn't work.

https://travis-ci.org/thoughtbot/hound/builds/48377766

screenshot 2015-01-26 11 07 30

**Comment by thorncp** [comment]
The branch I snapshotted is `bubbles`, and the seed is `1496`.

https://trello.com/c/8jnTDeQk

**Pull request closed without merging**
